service: txt-from-img
frameworkVersion: ">=1.34.0 <2.0.0"

custom:
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  tessdata: tessdata
  region: us-east-2

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    REGION: ${self:custom.region}
    TESSDATA_PREFIX: ${self:custom.tessdata}

layers:
  tesseractPython36:
    path: layers
    description: A Layer to support tesseract in Python 3.6 Lambda functions
    compatibleRuntimes:
      - python3.6
