version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6.1

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "Pipfile.lock" }}
            - deps-cache-

      - run:
          name: install dependencies
          command: |
            sudo apt install tesseract-ocr libtesseract-dev make
            sudo pip install pipenv
            pipenv install --system

      - save_cache:
          key: deps-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

jobs:
  function:
    <<: *defaults
    steps:
      - install
      - run: pipenv run pytest

workflows:
  version: 2

  tests:
    jobs:
      - function:
          filters:
            branches:
              only:
                - master
