version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6.1

commands:
  system:
    steps:
      - run:
          name: install system dependencies
          command: |
            sudo apt-get update --fix-missing
            sudo apt install gcc gcc-c++ make autoconf aclocal automake libtool \
                      libjpeg-devel libpng-devel libtiff-devel zlib-devel \
                      libzip-devel freetype-devel lcms2-devel libwebp-devel \
                      tcl-devel tk-devel
  leptonica:
    steps:
      - run:
          name: install leptonica
          command: |
            mkdir leptonica
            cd leptonica
            wget http://www.leptonica.org/source/leptonica-1.74.1.tar.gz
            tar -zxvf leptonica-*.tar.gz
            cd leptonica-*
            ./configure
            make
            sudo make install

  tesseract:
    steps:
      - run:
          name: install tesseract
          command: |
            git clone --branch 4.00.00alpha https://github.com/tesseract-ocr/tesseract.git
            cd tesseract
            ./autogen.sh
            ./configure --enable-debug
            LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
            sudo make install
  pydeps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "Pipfile.lock" }}
            - deps-cache-

      - run:
          name: install Python dependencies
          command: |
            sudo pip install pipenv
            pipenv install --system

      - save_cache:
          key: deps-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

jobs:
  function:
    <<: *defaults
    steps:
      - system
      - leptonica
      - tesseract
      - pydeps
      - run: pipenv run pytest

workflows:
  version: 2

  tests:
    jobs:
      - function:
          filters:
            branches:
              only:
                - master
