version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6.1

commands:
  system:
    steps:
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y git \
              libtesseract-dev \
              libleptonica-dev \
              tesseract-ocr-eng \
              tesseract-ocr \
              wget
            wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/4.0.0-1/tesseract.tar.xz | tar -xJf -
            sudo cp -rt /usr .tesseract/*

  pydeps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-{{ checksum "Pipfile.lock" }}
            - deps-cache-

      - run:
          name: Install Python dependencies
          command: |
            sudo pip install pipenv
            pipenv install --system

      - save_cache:
          key: deps-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

jobs:
  lambda:
    <<: *defaults
    steps:
      - system
      - pydeps
      - run: pipenv run pytest

workflows:
  version: 2

  tests:
    jobs:
      - lambda:
          filters:
            branches:
              only:
                - master
