version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6.1

commands:
  system:
    steps:
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y git \
              libtesseract-dev \
              libleptonica-dev \
              tesseract-ocr-eng \
              tesseract-ocr

  pydeps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-v3-{{ checksum "Pipfile.lock" }}
            - deps-cache-v3-

      - run:
          name: Install Python dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: Configure AWS cli
          command: |
            mkdir ~/.aws
            pipenv run  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            pipenv run  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            cp .circleci/aws_config ~/.aws/config

      - save_cache:
          key: deps-cache-v3-{{ checksum "Pipfile.lock" }}
          paths:
            - "/home/circleci/.local/share/virtualenvs"

  deploy:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-cache-v3-{{ checksum "Pipfile.lock" }}
            - deps-cache-v3-
      - run
          name: Deploy function to AWS
          command: |
          pipenv run aws s3 ls

jobs:
  lambda:
    <<: *defaults
    steps:
      - pydeps
      - system
      - run: make lint tests
      - deploy

workflows:
  version: 2

  tests:
    jobs:
      - lambda:
          filters:
            branches:
              only:
                - master
